### ISSUE TITLE
Missing Promise.allSettled() not found

### ISSUE THREAD

**Issue by natros** [akasha/akasha#35]
Hi, 

First I want to clarify that I don't know nothing about JavaScript so I could be wrong on this but I'm not finding Promise.allSettled() in akasha 0.30. 
Is this a bug?

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/allSettled

Thank you.

**Comment by realityforge** [comment]
That's a missing feature. It would be simple to add (roughly copy paste the Promise.all code and update documentation and potentially add a custom closure extern if the main closure repository does not have the extern). I will have a look at it next week but I would as just about to head away from the weekend.

**Comment by realityforge** [comment]
Added support for this in https://github.com/akasha/akasha/commit/eeab8733d84097504e73dc1d5371dc29ffb82943 and ereleased it as version `0.31`. This should be available in maven central within the hour or so. HTH
